version: '3'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_ALLOWED_HOSTS=45.61.160.38
      - DJANGO_CORS_ALLOWED_ORIGINS=http://45.61.160.38:3000
      # Add other required environment variables here
    volumes:
      - ./server:/app

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_ENDPOINT=http://45.61.160.38:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
